apiVersion: v1
kind: Pod
metadata:
  name: app-with-init
  labels:
    app: demo-init
spec:
  volumes:
  - name: config-volume
    emptyDir: {}

  initContainers:
  - name: init-config
    image: busybox
    command:
      - sh
      - -c
      - |
        cat <<EOF > /config/demo-config.yaml
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: demo-config
        EOF
        echo "Config file created by init container"
    volumeMounts:
    - name: config-volume
      mountPath: /config

  containers:
  - name: main-app
    image: busybox
    command:
      - sh
      - -c
      - |
        echo "==== Contents of generated config ===="
        cat /app/config/demo-config.yaml
        echo "======================================"
        sleep 3600
    volumeMounts:
    - name: config-volume
      mountPath: /app/config
