---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-reader-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: pod-reader-sa
    namespace: default
roleRef:
  kind: Role
  name: pod-reader-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-reader
  namespace: default
spec:
  serviceAccountName: pod-reader-sa
  containers:
    - name: reader
      image: bitnami/kubectl:latest
      command:
        - sh
        - -c
        - |
          echo "Listing pods using ServiceAccount permissions:"
          kubectl get pods --namespace=default
          kubectl get secrets
          sleep 3600
