apiVersion: v1
kind: Pod
metadata:
  name: nginx-sidecar
  namespace: test
  labels:
    app: nginx-sidecar
spec:
  volumes:
  - name: shared-logs
    emptyDir: {}

  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx
    command: ["/bin/sh"]
    args:
      - "-c"
      - |
        sed -i 's|access_log /var/log/nginx/access.log;|access_log /var/log/nginx/access.log;|' /etc/nginx/nginx.conf && \
        nginx -g 'daemon off;'

  - name: fluentd-sidecar
    image: fluent/fluentd:v1.14-debian-1
    volumeMounts:
    - name: shared-logs
      mountPath: /fluentd/log
    command: ["/bin/sh"]
    args:
      - "-c"
      - |
        tail -F /fluentd/log/access.log
