apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/data/my-static-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-using-static-pvc
spec:
  containers:
    - name: app
      image: busybox
      command:
        - sh
        - -c
        - |
          echo "Hello from Pod at $(date)" > /data/hello.txt
          sleep 3600
      volumeMounts:
        - mountPath: /data
          name: static-storage
  volumes:
    - name: static-storage
      persistentVolumeClaim:
        claimName: static-pvc
