apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Let's Encrypt staging ACME server
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: your-email@example.com  # <--- CHANGE THIS to your email
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: nginx
